apiVersion: v1
kind: Service
metadata:
  name: rstudio-copy
  labels:
    app: rstudio-copy
spec:
  selector:
    app: rstudio-copy
  ports:
    - port: 8787
      targetPort: 8787
      protocol: TCP
