apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: jmeegan607/data-portal-nginx:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: portal-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: htpasswd
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: portal-html
          configMap:
            name: portal-html
        - name: htpasswd
          secret:
            secretName: nginx-htpasswd
