apiVersion: v1                     # ConfigMaps use the core API
kind: ConfigMap                    # key-value store for non-sensitive config
metadata:
  name: dart-db-config             # name you reference from Deployments
data:
  DB_HOST: "host.docker.internal"  # TODO: in NGSC, replace with RDS endpoint
  DB_PORT: "5551"
  DB_NAME: "dart"
  DB_USER: "dart"
