apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/dart-db-config.yaml
  - config/dart-db-secret.yaml
  - config/test-scripts-configmap.yaml
  - rstudio/pvc.yaml
  - rstudio/deployment.yaml
  - rstudio/service.yaml
  - vscode/pvc.yaml
  - vscode/deployment.yaml
  - vscode/service.yaml
