apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: dart-db-config
    literals:
      - DB_HOST=host.docker.internal
      - DB_PORT=5551
      - DB_NAME=dart
      - DB_USER=dart
  - name: nginx-config
    files:
      - default.conf=nginx/default.conf
  - name: portal-html
    files:
      - index.html=nginx/index.html

resources:
  - config/dart-db-secret.yaml
  - config/test-scripts-configmap.yaml
  - nginx/deployment.yaml
  - nginx/service.yaml
  - nginx/htpasswd-secret.yaml
  - rstudio/pvc.yaml
  - rstudio/deployment.yaml
  - rstudio/service.yaml
  - vscode/pvc.yaml
  - vscode/deployment.yaml
  - vscode/service.yaml
