apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rstudio-pvc                        # name referenced by the deployment
  labels:
    app: rstudio
spec:
  accessModes:
    - ReadWriteOnce                        # one pod can read/write at a time
  resources:
    requests:
      storage: 5Gi                         # 5GB of persistent storage
